[package]
name = "penne"
version = "0.2.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]
edition = "2021"
publish = false

[dependencies]
enumset = "1.0"
anyhow = "^1.0"
thiserror = "^1.0"
ariadne = "0.1.5"
termcolor = "1.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
clap = { version = "4.0", features = ["derive"] }
llvm-sys = "60"

[dev-dependencies]
pretty_assertions = "0.6"

[[bin]]
name = "pennec"
path = "src/main.rs"
