[package]
name = "penne"
version = "0.1.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "^1.0"
thiserror = "^1.0"
llvm-sys = "60.*"
