[package]
name = "penne"
version = "0.1.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]
edition = "2021"
publish = false

[dependencies]
enumset = "1.0"
anyhow = "^1.0"
thiserror = "^1.0"
termcolor = "1.1"
log = "0.4"
clap = { version = "4.0", features = ["derive"] }
llvm-sys = "60"
env_logger = { version = "0.9", optional = true }

[dev-dependencies]
pretty_assertions = "0.6"

[[bin]]
name = "pennec"
path = "src/main.rs"

[features]
logging = ["env_logger"]
