[package]
name = "penne"
version = "0.1.0"
authors = ["Sander in 't Veld <sanderintveld@hotmail.com>"]
edition = "2021"
publish = false

[dependencies]
enumset = "1.0"
anyhow = "^1.0"
thiserror = "^1.0"
pretty_assertions = "0.6.*"
termcolor = "1.1"
clap = { version = "4.0", features = ["derive"] }
llvm-sys = "60"

[[bin]]
name = "pennec"
path = "src/main.rs"
