title: Penne Documentation
logo: /assets/images/penne_logo_500x160.png
favicon_ico: /assets/images/favicon.ico

safe: false

highlighter: rouge

plugins:
  - jekyll-redirect-from

theme: just-the-docs
