baseurl: /penne
title: Penne Documentation
logo: /assets/images/penne_logo_500x160.png
favicon_ico: /assets/images/favicon.ico

safe: false
highlighter: rouge

plugins:
  - jekyll-redirect-from

theme: just-the-docs
color_scheme: penne

search_enabled: true
aux_links:
  "Penne on GitHub":
    - 'https://github.com/SLiV9/penne'
heading_anchors: true
