# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'jekyll'
gem 'just-the-docs'

gem 'jekyll-avatar'
gem 'jekyll-coffeescript'
gem 'jekyll-commonmark-ghpages'
gem 'jekyll-default-layout'
gem 'jekyll-feed'
gem 'jekyll-gist'
gem 'jekyll-github-metadata'
gem 'jekyll-include-cache'
gem 'jekyll-mentions'
gem 'jekyll-optional-front-matter'
gem 'jekyll-paginate'
gem 'jekyll-readme-index'
gem 'jekyll-redirect-from'
gem 'jekyll-relative-links'
gem 'jekyll-remote-theme'
gem 'jekyll-sass-converter'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-swiss'
gem 'jekyll-titles-from-headings'
gem 'jemoji'
gem 'kramdown'
gem 'kramdown-parser-gfm'
gem 'liquid'
gem 'mercenary'
gem 'minima'
gem 'nokogiri'
gem 'rouge'
gem 'terminal-table'
