name: Rust

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:    
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Restore LLVM
      id: restore-llvm
      uses: actions/cache/restore@v3
      with:
        path: ./llvm
        key: llvm-10.0
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        cached: ${{ steps.restore-llvm.outputs.cache-hit }}
    - name: Cache LLVM
      uses: actions/cache/save@v3
      if: steps.restore-llvm.outputs.cache-hit != 'true'
      with:
        path: ./llvm
        key: llvm-10.0
    - name: Find llvm
      run: which llvm-config clang lli
    - name: Test llvm version
      run: llvm-config --version
    - name: Build linux
      run: cargo build --release
    - name: Package linux
      shell: bash
      run: |
        cd target/release
        tar czvf ../../penne-linux-x86_64.tar.gz penne
        cd -
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          penne-linux-x86_64.tar.gz
