name: Rust

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: ./llvm
        key: llvm-10.0
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Build linux
      run: cargo build --release
      env:
        LLVM_SYS_60_PREFIX: ./llvm
    - name: Package linux
      shell: bash
      run: |
        cd target/release
        tar czvf ../../penne-linux-x86_64.tar.gz penne
        cd -
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          penne-linux-x86_64.tar.gz
