name: Rust

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build linux
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Package linux
      run: tar czvf penne-linux-x86_64.tar.gz target/release/penne
    - name: Release linux
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: |
          penne-linux-x86_64.tar.gz
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build windows
      run: cargo build --release --verbose
    - name: Package windows
      run: 7z a penne-windows-x86_64.zip target/release/penne.exe
    - name: Release windows
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          penne-windows-x86_64.zip
